### ISSUE TITLE
Static members inside Activity

### ISSUE THREAD

**Issue by epishie** [tosinonikute/HackerNews#1]
Nice app.
I've noticed that some of the Activity classes have fields that are static that shouldn't be because these will definitely cause memory leaks when the activity is destroyed. Any particular reason why declare them as statics?

**Comment by tosinonikute** [comment]
Oh! 
Thanks for bringing that to my notice, that was a mistake on my part. Apart from the API & Constants class. There shouldn't be any need for static fields.
